const KEY='shipchain_shipments_v1';
const API='/api';
const token=()=>localStorage.getItem('shipchain_token');
const headers=()=>({'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})});
function getShipments(){return JSON.parse(localStorage.getItem(KEY)||'[]');}
function saveShipments(data){localStorage.setItem(KEY,JSON.stringify(data));}
function makeId(){return 'SHP-'+Math.floor(100000+Math.random()*900000);}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'API request failed');return r.json();}
function requireLogin(){if(!token()){location.href='login.html?next='+encodeURIComponent(location.pathname);return false;}return true;}
function trackingUrl(id){return new URL('tracking.html?id='+encodeURIComponent(id),location.href).href;}
function renderQr(target,text,size=180){if(!target||!window.QRCode)return;target.innerHTML='';new QRCode(target,{text,width:size,height:size,correctLevel:QRCode.CorrectLevel.M});}
function downloadQr(id){const canvas=document.querySelector('#createdQr canvas')||document.querySelector('#trackingQr canvas');if(!canvas)return alert('QR code is not available yet.');const a=document.createElement('a');a.download=id+'-QR.png';a.href=canvas.toDataURL('image/png');a.click();}
function printLabel(){window.print();}

const form=document.getElementById('shipmentForm');
if(form){form.addEventListener('submit',async e=>{e.preventDefault();if(!requireLogin())return;const receiverAccount=document.getElementById('receiverUserId');const payload={sender:sender.value.trim(),receiver:receiver.value.trim(),receiverUserId:receiverAccount?receiverAccount.value:'',product:product.value.trim(),source:source.value.trim(),destination:destination.value.trim(),mode:mode.value,delivery:delivery.value};if(!payload.receiverUserId){const box=document.getElementById('receiverError');if(box)box.textContent='Select a registered receiver account.';return;}try{const shipment=await api('/shipments',{method:'POST',body:JSON.stringify(payload)});showCreated(shipment);}catch(err){const box=document.getElementById('receiverError');if(box)box.textContent=err.message;const shipment={id:makeId(),...payload,status:'Created',createdAt:new Date().toISOString(),events:[{status:'Shipment Created',location:payload.source,time:new Date().toISOString(),verified:false},{status:'Picked Up',location:payload.source,time:null,verified:false},{status:'In Transit',location:'',time:null,verified:false},{status:'Arrived at Hub',location:'',time:null,verified:false},{status:'Out for Delivery',location:payload.destination,time:null,verified:false},{status:'Delivered',location:payload.destination,time:null,verified:false}]};const data=getShipments();data.unshift(shipment);saveShipments(data);showCreated(shipment);}});}
function showCreated(s){success.classList.remove('hidden');success.innerHTML=`<div class="qr-label"><div><span class="eyebrow">SHIPCHAIN SHIPPING LABEL</span><h3>${escapeHtml(s.product)}</h3><p><b>Shipment:</b> ${escapeHtml(s.id)}</p><p>${escapeHtml(s.source)} → ${escapeHtml(s.destination)}</p><p><b>Receiver:</b> ${escapeHtml(s.receiver)}</p></div><div id="createdQr" class="qr-box"></div></div><p><b>Scan the QR with a phone camera to open public tracking.</b></p><button type="button" class="btn secondary" onclick="downloadQr('${escapeHtml(s.id)}')">Download QR</button> <button type="button" class="btn secondary" onclick="printLabel()">Print Label</button><br><a href="tracking.html?id=${encodeURIComponent(s.id)}">Open tracking page →</a>`;renderQr(document.getElementById('createdQr'),trackingUrl(s.id));form.reset();}

const trackingForm=document.getElementById('trackingForm');
if(trackingForm)trackingForm.addEventListener('submit',e=>{e.preventDefault();showTracking(document.getElementById('shipmentId').value.trim());});
async function showTracking(id){const box=document.getElementById('trackingResult');let s;try{s=await api('/shipments/'+encodeURIComponent(id));}catch(err){s=getShipments().find(x=>x.id.toLowerCase()===id.toLowerCase());}if(!s){box.innerHTML='<div class="panel shipment-card"><h3>❌ Shipment not found</h3><p>Check the shipment ID and try again.</p></div>';return;}const publicUrl=trackingUrl(s.id);box.innerHTML=`<div class="panel shipment-card"><div class="table-head"><div><span class="eyebrow">SHIPMENT ${escapeHtml(s.id)}</span><h2>${escapeHtml(s.product)}</h2></div><span class="badge">${escapeHtml(s.status)}</span></div><p><b>${escapeHtml(s.source)}</b> → <b>${escapeHtml(s.destination)}</b> · ${escapeHtml(s.mode)}</p><p>Sender: ${escapeHtml(s.sender)} · Receiver: ${escapeHtml(s.receiver)}</p><div class="qr-section"><div id="trackingQr" class="qr-box"></div><div><b>Public tracking QR</b><p>Anyone can scan this code with a phone camera to open the shipment's public tracking page.</p><button type="button" class="btn secondary" onclick="downloadQr('${escapeHtml(s.id)}')">Download QR</button> <button type="button" class="btn secondary" onclick="printLabel()">Print Label</button><p><small>${escapeHtml(publicUrl)}</small></p></div></div><div class="timeline-list">${(s.events||[]).map(e=>`<div class="event ${e.time?'done':''}"><div class="event-dot"></div><div><b>${escapeHtml(e.status)}</b><br><small>${e.time?new Date(e.time).toLocaleString():'Pending'} ${e.location?'· '+escapeHtml(e.location):''} ${e.verified?'· 🔗 Verified':''}</small></div></div>`).join('')}</div><div class="panel" style="box-shadow:none;margin-top:10px;background:#f7f9fc"><b>Blockchain status:</b> ${s.blockchain_hash?'Verified on-chain':'Smart-contract integration ready'}<br><b>Proof of delivery:</b> ${escapeHtml(s.pod_status||'Pending')}</div><div id="podBox" style="margin-top:16px"></div></div>`;renderQr(document.getElementById('trackingQr'),publicUrl);renderPod(s);}

async function renderPod(s){const box=document.getElementById('podBox');if(!box)return;if(s.pod_status==='Verified'){box.innerHTML=`<h3>✅ Proof of Delivery Verified</h3><p>Verified at ${new Date(s.pod_verified_at).toLocaleString()}</p><p>Receiver signature recorded: ${s.pod_signature?'Yes':'No'}</p>${s.pod_photo_hash?`<p>Delivery photo hash: <code>${escapeHtml(s.pod_photo_hash)}</code></p><img src="/api/shipments/${encodeURIComponent(s.id)}/pod/photo" alt="Delivery proof" style="max-width:100%;border-radius:12px">`:''}`;return;}if(s.status!=='Out for Delivery'&&s.status!=='Delivered'){box.innerHTML='<p>Proof of delivery becomes available when the shipment is out for delivery.</p>';return;}box.innerHTML=`<h3>📦 Receiver Proof of Delivery</h3><p>Generate a one-time OTP, then confirm delivery with receiver signature and an optional delivery photo.</p><button class="btn secondary" id="otpBtn">Send / Generate OTP</button><div id="podForm" style="display:none;margin-top:12px"><input id="podOtp" placeholder="6-digit OTP" maxlength="6"><br><br><label>Receiver signature</label><br><canvas id="signaturePad" width="500" height="180" style="max-width:100%;border:1px solid #ccc;border-radius:8px;background:#fff"></canvas><br><button type="button" class="btn small secondary" id="clearSig">Clear signature</button><br><br><label>Delivery photo</label><input id="podPhoto" type="file" accept="image/*" capture="environment"><br><button class="btn primary" id="confirmPod" style="margin-top:12px">Confirm Delivery</button><div id="podMsg"></div></div>`;setupPod(s.id);}
function setupPod(id){const c=document.getElementById('signaturePad'),ctx=c.getContext('2d');ctx.lineWidth=2;let drawing=false;c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(drawing){ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()}};c.onpointerup=()=>drawing=false;c.onpointerleave=()=>drawing=false;document.getElementById('clearSig').onclick=()=>ctx.clearRect(0,0,c.width,c.height);document.getElementById('otpBtn').onclick=async()=>{try{const r=await api('/shipments/'+encodeURIComponent(id)+'/pod/request-otp',{method:'POST'});document.getElementById('podForm').style.display='block';document.getElementById('podMsg').innerHTML=`<p>OTP generated. Demo OTP: <b>${r.demoOtp||'sent securely'}</b></p>`;}catch(e){alert(e.message)}};document.getElementById('confirmPod').onclick=async()=>{const file=document.getElementById('podPhoto').files[0];let photo=null;if(file){if(file.size>5*1024*1024)return alert('Photo must be under 5MB');photo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}try{const r=await api('/shipments/'+encodeURIComponent(id)+'/pod/confirm',{method:'POST',body:JSON.stringify({otp:document.getElementById('podOtp').value,signature:c.toDataURL('image/png'),photo})});document.getElementById('podMsg').innerHTML='<p>✅ '+escapeHtml(r.message)+'</p>';showTracking(id);}catch(e){document.getElementById('podMsg').innerHTML='<p class="error">'+escapeHtml(e.message)+'</p>';}};}

async function renderDashboard(){let data=[];try{data=await api('/shipments');}catch(e){data=getShipments();}const total=document.getElementById('total');if(total)total.textContent=data.length;const transit=document.getElementById('transit');if(transit)transit.textContent=data.filter(s=>['Created','Picked Up','In Transit','Arrived at Hub','Out for Delivery'].includes(s.status)).length;const delivered=document.getElementById('delivered');if(delivered)delivered.textContent=data.filter(s=>s.status==='Delivered').length;const el=document.getElementById('shipmentTable');if(!el)return;if(!data.length){el.innerHTML='<div class="empty">No shipments yet. Create your first shipment.</div>';return;}el.innerHTML='<div class="table-scroll"><table><thead><tr><th>ID</th><th>Product</th><th>Route</th><th>Status</th><th>Action</th></tr></thead><tbody>'+data.map(s=>`<tr><td><b>${escapeHtml(s.id)}</b></td><td>${escapeHtml(s.product)}</td><td>${escapeHtml(s.source)} → ${escapeHtml(s.destination)}</td><td><span class="badge">${escapeHtml(s.status)}</span></td><td><a href="tracking.html?id=${encodeURIComponent(s.id)}">View</a></td></tr>`).join('')+'</tbody></table></div>';}
function clearShipments(){if(confirm('Delete all prototype shipment data from this browser?')){localStorage.removeItem(KEY);location.reload();}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
const loginForm=document.getElementById('loginForm');if(loginForm)loginForm.addEventListener('submit',async e=>{e.preventDefault();const box=document.getElementById('loginMessage');try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email:loginEmail.value,password:loginPassword.value})});localStorage.setItem('shipchain_token',data.token);localStorage.setItem('shipchain_user',JSON.stringify(data.user));location.href=new URLSearchParams(location.search).get('next')||'dashboard.html';}catch(err){box.textContent=err.message;box.className='error';}});
const registerForm=document.getElementById('registerForm');if(registerForm)registerForm.addEventListener('submit',async e=>{e.preventDefault();const box=document.getElementById('registerMessage');try{const data=await api('/auth/register',{method:'POST',body:JSON.stringify({email:registerEmail.value,password:registerPassword.value,role:registerRole.value})});localStorage.setItem('shipchain_token',data.token);localStorage.setItem('shipchain_user',JSON.stringify(data.user));location.href='dashboard.html';}catch(err){box.textContent=err.message;box.className='error';}});
