const KEY='shipchain_shipments_v1';
const API='/api';
const token=()=>localStorage.getItem('shipchain_token');
const headers=()=>({'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})});
function getShipments(){return JSON.parse(localStorage.getItem(KEY)||'[]');}
function saveShipments(data){localStorage.setItem(KEY,JSON.stringify(data));}
function makeId(){return 'SHP-'+Math.floor(100000+Math.random()*900000);}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'API request failed');return r.json();}
function requireLogin(){if(!token()){location.href='login.html?next='+encodeURIComponent(location.pathname);return false;}return true;}

const form=document.getElementById('shipmentForm');
if(form){
 form.addEventListener('submit',async e=>{e.preventDefault();if(!requireLogin())return;const payload={sender:sender.value.trim(),receiver:receiver.value.trim(),product:product.value.trim(),source:source.value.trim(),destination:destination.value.trim(),mode:mode.value,delivery:delivery.value};
 try{const shipment=await api('/shipments',{method:'POST',body:JSON.stringify(payload)});showCreated(shipment)}catch(err){const shipment={id:makeId(),...payload,status:'Created',createdAt:new Date().toISOString(),events:[{status:'Shipment Created',location:payload.source,time:new Date().toISOString(),verified:false},{status:'Picked Up',location:payload.source,time:null,verified:false},{status:'In Transit',location:'',time:null,verified:false},{status:'Arrived at Hub',location:'',time:null,verified:false},{status:'Out for Delivery',location:payload.destination,time:null,verified:false},{status:'Delivered',location:payload.destination,time:null,verified:false}]};const data=getShipments();data.unshift(shipment);saveShipments(data);showCreated(shipment);}}
 );
}
function showCreated(s){success.classList.remove('hidden');success.innerHTML=`<b>✅ Shipment created successfully.</b><br>Shipment ID: <strong>${escapeHtml(s.id)}</strong><br><a href="tracking.html?id=${encodeURIComponent(s.id)}">Open tracking page →</a>`;form.reset();}

const trackingForm=document.getElementById('trackingForm');
if(trackingForm)trackingForm.addEventListener('submit',e=>{e.preventDefault();showTracking(document.getElementById('shipmentId').value.trim());});
async function showTracking(id){const box=document.getElementById('trackingResult');let s;try{s=await api('/shipments/'+encodeURIComponent(id));}catch(err){s=getShipments().find(x=>x.id.toLowerCase()===id.toLowerCase());}if(!s){box.innerHTML='<div class="panel shipment-card"><h3>❌ Shipment not found</h3><p>Check the shipment ID and try again.</p></div>';return;}
 box.innerHTML=`<div class="panel shipment-card"><div class="table-head"><div><span class="eyebrow">SHIPMENT ${escapeHtml(s.id)}</span><h2>${escapeHtml(s.product)}</h2></div><span class="badge">${escapeHtml(s.status)}</span></div><p><b>${escapeHtml(s.source)}</b> → <b>${escapeHtml(s.destination)}</b> · ${escapeHtml(s.mode)}</p><p>Sender: ${escapeHtml(s.sender)} · Receiver: ${escapeHtml(s.receiver)}</p><div class="timeline-list">${s.events.map(e=>`<div class="event ${e.time?'done':''}"><div class="event-dot"></div><div><b>${escapeHtml(e.status)}</b><br><small>${e.time?new Date(e.time).toLocaleString():'Pending'} ${e.location?'· '+escapeHtml(e.location):''} ${e.verified?'· 🔗 Verified':''}</small></div></div>`).join('')}</div><div class="panel" style="box-shadow:none;margin-top:10px;background:#f7f9fc"><b>Blockchain status:</b> ${s.blockchain_hash?'Verified on-chain':'Smart-contract integration ready'} </div></div>`;}

async function renderDashboard(){let data=[];try{data=await api('/shipments');}catch(e){data=getShipments();}const total=document.getElementById('total');if(total)total.textContent=data.length;const transit=document.getElementById('transit');if(transit)transit.textContent=data.filter(s=>['Created','Picked Up','In Transit','Arrived at Hub','Out for Delivery'].includes(s.status)).length;const delivered=document.getElementById('delivered');if(delivered)delivered.textContent=data.filter(s=>s.status==='Delivered').length;const el=document.getElementById('shipmentTable');if(!el)return;if(!data.length){el.innerHTML='<div class="empty">No shipments yet. Create your first shipment.</div>';return;}el.innerHTML='<div class="table-scroll"><table><thead><tr><th>ID</th><th>Product</th><th>Route</th><th>Status</th><th>Action</th></tr></thead><tbody>'+data.map(s=>`<tr><td><b>${escapeHtml(s.id)}</b></td><td>${escapeHtml(s.product)}</td><td>${escapeHtml(s.source)} → ${escapeHtml(s.destination)}</td><td><span class="badge">${escapeHtml(s.status)}</span></td><td><a href="tracking.html?id=${encodeURIComponent(s.id)}">View</a></td></tr>`).join('')+'</tbody></table></div>';}
function clearShipments(){if(confirm('Delete all prototype shipment data from this browser?')){localStorage.removeItem(KEY);location.reload();}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

const loginForm=document.getElementById('loginForm');
if(loginForm)loginForm.addEventListener('submit',async e=>{e.preventDefault();const box=document.getElementById('loginMessage');try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email:loginEmail.value,password:loginPassword.value})});localStorage.setItem('shipchain_token',data.token);localStorage.setItem('shipchain_user',JSON.stringify(data.user));const next=new URLSearchParams(location.search).get('next')||'dashboard.html';location.href=next;}catch(err){box.textContent=err.message;box.className='error';}});
const registerForm=document.getElementById('registerForm');
if(registerForm)registerForm.addEventListener('submit',async e=>{e.preventDefault();const box=document.getElementById('registerMessage');try{const data=await api('/auth/register',{method:'POST',body:JSON.stringify({email:registerEmail.value,password:registerPassword.value,role:registerRole.value})});localStorage.setItem('shipchain_token',data.token);localStorage.setItem('shipchain_user',JSON.stringify(data.user));location.href='dashboard.html';}catch(err){box.textContent=err.message;box.className='error';}});
