require('dotenv').config();
const express=require('express');const cors=require('cors');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');const {randomUUID,createHash}=require('crypto');const {ethers}=require('ethers');
const app=express(),PORT=Number(process.env.PORT)||3000,JWT_SECRET=process.env.JWT_SECRET||'change-this-secret-in-production',DB_FILE=process.env.DB_FILE||'shipchain.db',db=new Database(DB_FILE);
if(process.env.NODE_ENV==='production'&&(!process.env.JWT_SECRET||process.env.JWT_SECRET==='change-this-secret-in-production'))throw new Error('JWT_SECRET must be set to a strong production secret');
const configuredOrigins=(process.env.CORS_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean);const corsOptions=process.env.NODE_ENV==='production'?{origin:(origin,cb)=>{if(!origin||configuredOrigins.includes(origin))return cb(null,true);cb(new Error('Origin not allowed by CORS'));}}:{};
app.use(cors(corsOptions));app.use(express.json({limit:process.env.JSON_BODY_LIMIT||'12mb'}));app.use(express.static(path.join(__dirname)));
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator',created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS shipments(id TEXT PRIMARY KEY,sender TEXT NOT NULL,receiver TEXT NOT NULL,product TEXT NOT NULL,source TEXT NOT NULL,destination TEXT NOT NULL,mode TEXT NOT NULL,delivery TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,blockchain_hash TEXT,blockchain_status TEXT DEFAULT 'Pending',pod_status TEXT DEFAULT 'Pending',pod_verified_at TEXT,pod_otp_hash TEXT,pod_otp_expires TEXT,pod_attempts INTEGER DEFAULT 0,pod_signature TEXT,pod_photo TEXT,pod_photo_hash TEXT,receiver_user_id TEXT);CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,shipment_id TEXT NOT NULL,status TEXT NOT NULL,location TEXT,time TEXT,verified INTEGER DEFAULT 0,tx_hash TEXT,FOREIGN KEY(shipment_id) REFERENCES shipments(id));`);
for(const c of ["blockchain_status TEXT DEFAULT 'Pending'","pod_status TEXT DEFAULT 'Pending'","pod_verified_at TEXT","pod_otp_hash TEXT","pod_otp_expires TEXT","pod_attempts INTEGER DEFAULT 0","pod_signature TEXT","pod_photo TEXT","pod_photo_hash TEXT","receiver_user_id TEXT"]){try{db.exec(`ALTER TABLE shipments ADD COLUMN ${c}`)}catch(e){}}
const makeId=()=>`SHP-${Math.floor(100000+Math.random()*900000)}`;const sha=v=>createHash('sha256').update(v).digest('hex');
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired token'})}}
function requireRole(...roles){return (req,res,next)=>{if(!req.user)return res.status(401).json({error:'Authentication required'});if(!roles.includes(req.user.role))return res.status(403).json({error:`Forbidden: ${roles.join(' or ')} role required. Current role: ${req.user.role||'unknown'}`});next()}}
function requireShipmentReceiver(req,res,next){const s=db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id);if(!s)return res.status(404).json({error:'Shipment not found'});const userId=String(req.user.id||'').toLowerCase(),email=String(req.user.email||'').toLowerCase(),assignedId=String(s.receiver_user_id||'').toLowerCase(),receiver=String(s.receiver||'').trim().toLowerCase();if(!((assignedId&&assignedId===userId)||(!assignedId&&(receiver===email||receiver===userId))))return res.status(403).json({error:'Forbidden: this shipment is not assigned to the authenticated receiver'});req.shipment=s;next()}
function shipment(row){if(!row)return null;const events=db.prepare('SELECT * FROM events WHERE shipment_id=? ORDER BY rowid').all(row.id);return {...row,events:events.map(e=>({...e,verified:Boolean(e.verified)}))}}
function chain(){if(!process.env.BLOCKCHAIN_RPC_URL||!process.env.BLOCKCHAIN_PRIVATE_KEY||!process.env.CONTRACT_ADDRESS||!process.env.CONTRACT_ABI)return null;try{const p=new ethers.JsonRpcProvider(process.env.BLOCKCHAIN_RPC_URL),w=new ethers.Wallet(process.env.BLOCKCHAIN_PRIVATE_KEY,p);return new ethers.Contract(process.env.CONTRACT_ADDRESS,JSON.parse(process.env.CONTRACT_ABI),w)}catch(e){return null}}
async function chainUpdate(id,status,location){const c=chain();if(!c)return null;const tx=await c.updateShipment(id,status,location);await tx.wait();return tx.hash}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'ShipChain API',blockchain:!!chain(),time:new Date().toISOString()}));
app.post('/api/auth/register',(req,res)=>{try{const{email,password,role='operator'}=req.body;if(!email||!password||password.length<6)return res.status(400).json({error:'Valid email and password (6+ characters) required'});if(role==='transporter'||role==='admin')return res.status(403).json({error:'Public registration cannot create transporter or admin accounts. A transporter account must be created or approved by an administrator.'});const safeRole=['operator','receiver'].includes(role)?role:'operator',hash=bcrypt.hashSync(password,10),userId=randomUUID();db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(userId,email.toLowerCase(),hash,safeRole,new Date().toISOString());const token=jwt.sign({id:userId,email:email.toLowerCase(),role:safeRole},JWT_SECRET,{expiresIn:'7d'});res.status(201).json({token,user:{id:userId,email:email.toLowerCase(),role:safeRole}})}catch(e){res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',(req,res)=>{const{email,password}=req.body,u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password))return res.status(401).json({error:'Invalid credentials'});res.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'}),user:{id:u.id,email:u.email,role:u.role}})});app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/receivers',auth,requireRole('admin','operator'),(req,res)=>res.json(db.prepare("SELECT id,email,created_at FROM users WHERE role='receiver' ORDER BY email ASC").all()));
app.get('/api/receiver/shipments',auth,requireRole('receiver'),(req,res)=>{const rows=db.prepare('SELECT id,sender,receiver,product,source,destination,mode,delivery,status,created_at,blockchain_status,pod_status,pod_verified_at,receiver_user_id FROM shipments WHERE receiver_user_id=? ORDER BY created_at DESC').all(req.user.id);res.json(rows)});
app.post('/api/admin/users',auth,requireRole('admin'),(req,res)=>{try{const{email,password,role}=req.body;if(!email||!password||password.length<6)return res.status(400).json({error:'Valid email and password (6+ characters) required'});if(!['operator','transporter','receiver'].includes(role))return res.status(400).json({error:'Invalid account role'});const userId=randomUUID(),hash=bcrypt.hashSync(password,10);db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(userId,email.toLowerCase(),hash,role,new Date().toISOString());res.status(201).json({message:`${role} account created by admin`,user:{id:userId,email:email.toLowerCase(),role}})}catch(e){res.status(409).json({error:'Email already registered'})}});
app.get('/api/admin/users',auth,requireRole('admin'),(req,res)=>res.json(db.prepare('SELECT id,email,role,created_at FROM users ORDER BY created_at DESC').all()));
app.get('/api/stats',(req,res)=>{const total=db.prepare('SELECT COUNT(*) c FROM shipments').get().c,transit=db.prepare("SELECT COUNT(*) c FROM shipments WHERE status!='Delivered'").get().c,delivered=db.prepare("SELECT COUNT(*) c FROM shipments WHERE status='Delivered'").get().c,verified=db.prepare("SELECT COUNT(*) c FROM shipments WHERE blockchain_status='Verified'").get().c,pod=db.prepare("SELECT COUNT(*) c FROM shipments WHERE pod_status='Verified'").get().c;res.json({total,transit,delivered,verified,podVerified:pod})});
app.get('/api/shipments',(req,res)=>res.json(db.prepare('SELECT * FROM shipments ORDER BY created_at DESC').all().map(shipment)));app.get('/api/shipments/:id',(req,res)=>{const s=shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id));if(!s)return res.status(404).json({error:'Shipment not found'});res.json(s)});
app.post('/api/shipments',auth,async(req,res)=>{try{const{sender,receiver,receiverUserId,product,source,destination,mode='Road',delivery}=req.body;if(!sender||!receiver||!product||!source||!destination||!delivery)return res.status(400).json({error:'Missing required shipment fields'});let receiverUserIdValue=null;if(receiverUserId){const receiverUser=db.prepare('SELECT id,email,role FROM users WHERE id=?').get(receiverUserId);if(!receiverUser)return res.status(400).json({error:'Receiver account not found'});if(receiverUser.role!=='receiver')return res.status(400).json({error:'receiverUserId must belong to a receiver account'});receiverUserIdValue=receiverUser.id;}else{const matchingReceiver=db.prepare("SELECT id,email FROM users WHERE role='receiver' AND lower(email)=lower(?)").get(receiver.trim());if(matchingReceiver)receiverUserIdValue=matchingReceiver.id;}const sid=makeId(),now=new Date().toISOString();db.prepare('INSERT INTO shipments(id,sender,receiver,product,source,destination,mode,delivery,status,created_at,blockchain_hash,blockchain_status,pod_status,receiver_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(sid,sender,receiver,product,source,destination,mode,delivery,'Created',now,null,'Pending','Pending',receiverUserIdValue);const ins=db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?,?)');[['Shipment Created',source,now,0,null],['Picked Up',source,null,0,null],['In Transit','',null,0,null],['Arrived at Hub','',null,0,null],['Out for Delivery',destination,null,0,null],['Delivered',destination,null,0,null]].forEach(e=>ins.run(randomUUID(),sid,...e));res.status(201).json(shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(sid)))}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/shipments/:id/status',auth,requireRole('transporter'),async(req,res)=>{try{const{status,location=''}=req.body,allowed=['Created','Picked Up','In Transit','Arrived at Hub','Out for Delivery','Delivered'];if(!allowed.includes(status))return res.status(400).json({error:'Invalid shipment status'});const s=shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id));if(!s)return res.status(404).json({error:'Shipment not found'});const now=new Date().toISOString();db.prepare('UPDATE shipments SET status=? WHERE id=?').run(status,req.params.id);const event=s.events.find(e=>e.status===status&&!e.time);if(event)db.prepare('UPDATE events SET time=?,location=? WHERE id=?').run(now,location,event.id);let hash=null;try{hash=await chainUpdate(req.params.id,status,location)}catch(e){}if(hash){db.prepare("UPDATE shipments SET blockchain_hash=?,blockchain_status='Verified' WHERE id=?").run(hash,req.params.id);if(event)db.prepare('UPDATE events SET verified=1,tx_hash=? WHERE id=?').run(hash,event.id)}res.json(shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id)))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/shipments/:id/pod/request-otp',auth,requireRole('receiver'),requireShipmentReceiver,(req,res)=>{const s=req.shipment;if(s.status!=='Out for Delivery'&&s.status!=='Delivered')return res.status(400).json({error:'Shipment is not ready for delivery confirmation'});const otp=String(Math.floor(100000+Math.random()*900000)),expires=new Date(Date.now()+10*60*1000).toISOString();db.prepare('UPDATE shipments SET pod_otp_hash=?,pod_otp_expires=?,pod_attempts=0,pod_status=\'OTP Sent\' WHERE id=?').run(sha(otp),expires,req.params.id);const response={message:'OTP generated for demonstration. In production send it by SMS/email.',expiresAt:expires};if(process.env.NODE_ENV!=='production')response.demoOtp=otp;res.json(response)});
app.post('/api/shipments/:id/pod/confirm',auth,requireRole('receiver'),requireShipmentReceiver,(req,res)=>{const{otp,signature,photo}=req.body,s=req.shipment;if(s.pod_status==='Verified')return res.status(400).json({error:'Proof of delivery already verified'});if(!s.pod_otp_hash||!s.pod_otp_expires)return res.status(400).json({error:'Request a delivery OTP first'});if((s.pod_attempts||0)>=5)return res.status(429).json({error:'Too many OTP attempts'});if(typeof otp!=='string'||!/^[0-9]{6}$/.test(otp))return res.status(400).json({error:'OTP must be exactly 6 numeric digits'});if(new Date(s.pod_otp_expires)<=new Date())return res.status(400).json({error:'OTP expired'});if(sha(otp)!==s.pod_otp_hash){db.prepare('UPDATE shipments SET pod_attempts=pod_attempts+1 WHERE id=?').run(req.params.id);return res.status(400).json({error:'Invalid OTP'})}if(!signature||typeof signature!=='string'||signature.length<20)return res.status(400).json({error:'Receiver signature is required'});if(photo&&!String(photo).startsWith('data:image/'))return res.status(400).json({error:'Photo must be a base64 data image'});const now=new Date().toISOString(),photoHash=photo?sha(photo):null;db.prepare("UPDATE shipments SET status='Delivered',pod_status='Verified',pod_verified_at=?,pod_otp_hash=NULL,pod_otp_expires=NULL,pod_attempts=0,pod_signature=?,pod_photo=?,pod_photo_hash=? WHERE id=?").run(now,signature,photo||null,photoHash,req.params.id);const ev=db.prepare("SELECT * FROM events WHERE shipment_id=? AND status='Delivered'").get(req.params.id);if(ev)db.prepare('UPDATE events SET time=?,location=?,verified=1 WHERE id=?').run(now,s.destination,ev.id);res.json({message:'Proof of delivery verified',shipment:shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id))})});
app.get('/api/shipments/:id/pod',auth,requireRole('receiver'),requireShipmentReceiver,(req,res)=>{const s=req.shipment;res.json({proof:{id:s.id,status:s.status,pod_status:s.pod_status,pod_verified_at:s.pod_verified_at,pod_signature:s.pod_signature,pod_photo_hash:s.pod_photo_hash},hasPhoto:Boolean(s.pod_photo_hash),hasSignature:Boolean(s.pod_signature)})});
app.get('/api/shipments/:id/pod/photo',auth,requireRole('receiver'),requireShipmentReceiver,(req,res)=>{const s=req.shipment;if(!s.pod_photo)return res.status(404).send('Photo not found');const m=String(s.pod_photo).match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)return res.status(404).send('Invalid photo');res.set('Content-Type',m[1]);res.send(Buffer.from(m[2],'base64'))});
app.get('/api/shipments/:id/risk',(req,res)=>{const s=shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id));if(!s)return res.status(404).json({error:'Shipment not found'});const due=new Date(s.delivery),days=Math.ceil((due-Date.now())/86400000),completed=s.events.filter(e=>e.time).length;let score=20;if(days<1&&s.status!=='Delivered')score+=45;if(days<3&&s.status!=='Delivered')score+=20;if(completed<2)score+=10;if(s.mode==='Air')score-=5;score=Math.max(5,Math.min(95,score));res.json({shipmentId:s.id,score,risk:score>=70?'High':score>=40?'Medium':'Low',daysUntilDue:days})});
app.get('*',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'API route not found'}):res.sendFile(path.join(__dirname,'index.html')));
if(require.main===module){app.listen(PORT,()=>console.log(`ShipChain running on http://localhost:${PORT}`));}
module.exports={app,db};