module.exports={
  rootDir:'.',
  testEnvironment:'node',
  testMatch:['<rootDir>/integration/**/*.test.js'],
  setupFiles:['<rootDir>/integration/env.js'],
  setupFilesAfterEnv:['<rootDir>/integration/setup.js'],
  testTimeout:15000,
  clearMocks:true,
  restoreMocks:true
};
