module.exports={
  rootDir:'.',
  testEnvironment:'node',
  testMatch:['integration/**/*.test.js'],
  setupFiles:['integration/env.js'],
  setupFilesAfterEnv:['integration/setup.js'],
  testTimeout:15000,
  clearMocks:true,
  restoreMocks:true
};
