module.exports={
  testEnvironment:'node',
  testMatch:['**/tests/integration/**/*.test.js'],
  setupFiles:['<rootDir>/tests/integration/env.js'],
  setupFilesAfterEnv:['<rootDir>/tests/integration/setup.js'],
  testTimeout:15000,
  clearMocks:true,
  restoreMocks:true
};
